### ISSUE TITLE
Textures not working properly

### ISSUE THREAD

**Issue by LOLOLOL08** [Moo-Ack-Productions/MCprep#512]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

When Impoprting a sculk/sculk vein trough the spawn Block Models menu those blocks spawn mith a wrong texture. When stretching the block on the z-axys  and make it 4 blocks high the texture works again.

### What steps are needed to produce the bug?

spawn  sculk/ sculk vein

### What version of MCprep are you using?

3.5.1

### What version of Blender are you using?

4.01

**Comment by zNightlord** [comment]
Did you try prep material with animated texture ticked yet?

**Comment by LOLOLOL08** [comment]
Yes! So do I need to replace the 4 block high texture with a 1 block texture

**Comment by StandingPadAnimations** [comment]
Although this is resolved with “Animate Textures”, I'm going to add this to the MCprep 3.6.1 milestone. The goal is to get these animated textures to be properly scaled when “Animate Textures” is disabled.

**Comment by zNightlord** [comment]
This should be resolved now. Closing?

**Comment by StandingPadAnimations** [comment]
The core issue of UVs not being properly scaled without animated textures enabled still exists as far as I know, so we'll keep this open

**Comment by zNightlord** [comment]
I thought I fixed that in #655, block model spawn sculk (vein) should their adjusted the uv scaling.

<img width="2289" height="1410" alt="Image" src="https://github.com/user-attachments/assets/23fa8a6d-a72b-4a0a-80ea-547292a34587" />

**Comment by StandingPadAnimations** [comment]
While the issue was originally reported with sculk, it impacts all blocks with animated textures, such as sea lanterns

**Comment by zNightlord** [comment]
> While the issue was originally reported with sculk, it impacts all blocks with animated textures, such as sea lanterns

Yeah it applied to every block with the texture with odd resolution?   
https://github.com/Moo-Ack-Productions/MCprep/blob/master/MCprep_addon/spawner/mcmodel.py#L570-L595

Edit: it's same as #646 right?
